[2020-08-27 15:43:03,805]:[handler.py]:[line:242]:INFO: 127.0.0.1 - - [2020-08-27 15:43:03] "GET /webchat HTTP/1.1" 200 1832 0.091450
[2020-08-27 15:43:04,274]:[handler.py]:[line:242]:INFO: 127.0.0.1 - - [2020-08-27 15:43:04] "GET /favicon.ico HTTP/1.1" 404 341 0.002990
[2020-08-27 15:45:20,792]:[handler.py]:[line:242]:INFO: 127.0.0.1 - - [2020-08-27 15:45:20] "GET /webchat HTTP/1.1" 200 1832 0.015958
[2020-08-27 15:45:36,176]:[handler.py]:[line:242]:INFO: 127.0.0.1 - - [2020-08-27 15:45:36] "GET /webchat HTTP/1.1" 200 1832 1.934370
[2020-08-27 15:47:14,851]:[handler.py]:[line:242]:INFO: 127.0.0.1 - - [2020-08-27 15:47:14] "GET /webchat HTTP/1.1" 200 1831 0.014985
[2020-08-27 16:09:12,117]:[handler.py]:[line:242]:INFO: 127.0.0.1 - - [2020-08-27 16:09:12] "GET /webchat HTTP/1.1" 200 1832 0.016954
[2020-08-27 16:09:14,218]:[handler.py]:[line:242]:INFO: 127.0.0.1 - - [2020-08-27 16:09:14] "GET /webchat HTTP/1.1" 200 1832 0.000997
[2020-08-27 16:13:15,640]:[handler.py]:[line:242]:INFO: 127.0.0.1 - - [2020-08-27 16:13:15] "GET /webchat HTTP/1.1" 200 1844 0.023609
[2020-08-27 16:13:16,902]:[handler.py]:[line:242]:INFO: 127.0.0.1 - - [2020-08-27 16:13:16] "GET /webchat HTTP/1.1" 200 1844 0.001994
[2020-08-27 16:13:25,766]:[app.py]:[line:1890]:ERROR: Exception on /user/chat [GET]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_restful\__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_restful\__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "d:\Code\env\restful-token\restful-token\app\web\chat.py", line 15, in get
    username = g.friendSeqid
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\werkzeug\local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: '_AppCtxGlobals' object has no attribute 'friendSeqid'
[2020-08-27 16:14:29,271]:[handler.py]:[line:242]:INFO: 127.0.0.1 - - [2020-08-27 16:14:29] "GET /webchat HTTP/1.1" 200 1844 0.015986
[2020-08-27 16:14:30,719]:[handler.py]:[line:242]:INFO: 127.0.0.1 - - [2020-08-27 16:14:30] "GET /webchat HTTP/1.1" 200 1844 0.001993
[2020-08-27 16:44:51,477]:[handler.py]:[line:242]:INFO: 127.0.0.1 - - [2020-08-27 16:44:51] "GET /webchat HTTP/1.1" 200 1840 0.073686
[2020-08-27 16:44:53,173]:[handler.py]:[line:242]:INFO: 127.0.0.1 - - [2020-08-27 16:44:53] "GET /favicon.ico HTTP/1.1" 404 341 0.002008
[2020-08-27 16:45:18,038]:[handler.py]:[line:242]:INFO: 127.0.0.1 - - [2020-08-27 16:45:18] "GET /webchat HTTP/1.1" 200 1840 0.030794
[2020-08-27 16:47:52,124]:[app.py]:[line:1890]:ERROR: Exception on /user/chat [GET]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_restful\__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_restful\__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "d:\Code\env\restful-token\restful-token\app\web\chat.py", line 24, in get
    msg_dict = json.loads(msg)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2020-08-27 16:49:41,960]:[app.py]:[line:1890]:ERROR: Exception on /user/chat [GET]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_restful\__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_restful\__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "d:\Code\env\restful-token\restful-token\app\web\chat.py", line 24, in get
    msg_dict = json.loads(msg)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2020-08-27 16:51:05,413]:[handler.py]:[line:242]:INFO: 127.0.0.1 - - [2020-08-27 16:51:05] "GET /main HTTP/1.1" 200 7086 9.976118
[2020-08-27 16:51:06,015]:[handler.py]:[line:242]:INFO: 127.0.0.1 - - [2020-08-27 16:51:06] "GET /favicon.ico HTTP/1.1" 404 341 0.002991
[2020-08-27 16:51:18,134]:[handler.py]:[line:242]:INFO: 127.0.0.1 - - [2020-08-27 16:51:18] "GET /main HTTP/1.1" 200 7650 0.046267
[2020-08-27 16:52:46,689]:[handler.py]:[line:242]:INFO: 127.0.0.1 - - [2020-08-27 16:52:46] "GET /webchat HTTP/1.1" 200 1840 0.001997
[2020-08-27 16:53:07,229]:[handler.py]:[line:242]:INFO: 127.0.0.1 - - [2020-08-27 16:53:07] "GET /webchat HTTP/1.1" 200 1840 0.001994
[2020-08-27 16:58:56,964]:[app.py]:[line:1890]:ERROR: Exception on /user/chat [GET]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_restful\__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_restful\__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "d:\Code\env\restful-token\restful-token\app\web\chat.py", line 24, in get
    msg_dict = json.loads(msg)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2020-08-27 16:59:15,168]:[app.py]:[line:1890]:ERROR: Exception on /user/chat [GET]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_restful\__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_restful\__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "d:\Code\env\restful-token\restful-token\app\web\chat.py", line 24, in get
    msg_dict = json.loads(msg)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2020-08-27 16:59:15,176]:[app.py]:[line:1890]:ERROR: Exception on /user/chat [GET]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_restful\__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_restful\__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "d:\Code\env\restful-token\restful-token\app\web\chat.py", line 24, in get
    msg_dict = json.loads(msg)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2020-08-27 16:59:36,684]:[app.py]:[line:1890]:ERROR: Exception on /user/chat [GET]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_restful\__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_restful\__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "d:\Code\env\restful-token\restful-token\app\web\chat.py", line 24, in get
    msg_dict = json.loads(msg)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
